name: CI/CD workflow to Railway

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: dr0pdatabase/nginx-ssl
  TAG: latest

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build . -t ${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Login to DockerHub 
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push to DockerHub
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Add Railway to PATH
        run: echo "${HOME}/.railway/bin" >> $GITHUB_PATH

      - name: Login to Railway
        run: railway login --token ${{ secrets.RAILWAY_API_KEY }}

      - name: Deploy to Railway
        run: railway up --project ${{ secrets.RAILWAY_PROJECT_ID }}